// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metrics.proto

package metrics

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Batch struct {
	Events               []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Batch) Reset()         { *m = Batch{} }
func (m *Batch) String() string { return proto.CompactTextString(m) }
func (*Batch) ProtoMessage()    {}
func (*Batch) Descriptor() ([]byte, []int) {
	return fileDescriptor_6039342a2ba47b72, []int{0}
}

func (m *Batch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Batch.Unmarshal(m, b)
}
func (m *Batch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Batch.Marshal(b, m, deterministic)
}
func (m *Batch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Batch.Merge(m, src)
}
func (m *Batch) XXX_Size() int {
	return xxx_messageInfo_Batch.Size(m)
}
func (m *Batch) XXX_DiscardUnknown() {
	xxx_messageInfo_Batch.DiscardUnknown(m)
}

var xxx_messageInfo_Batch proto.InternalMessageInfo

func (m *Batch) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type Event struct {
	Signature  string `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	TargetId   string `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	IsProvider bool   `protobuf:"varint,3,opt,name=is_provider,json=isProvider,proto3" json:"is_provider,omitempty"`
	// Types that are valid to be assigned to Metric:
	//	*Event_VersionPayload
	//	*Event_SessionEventPayload
	//	*Event_SessionStatisticsPayload
	//	*Event_ProposalPayload
	//	*Event_SessionConnectErrorPayload
	//	*Event_SessionConnectSuccessPayload
	Metric               isEvent_Metric `protobuf_oneof:"metric"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_6039342a2ba47b72, []int{1}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *Event) GetTargetId() string {
	if m != nil {
		return m.TargetId
	}
	return ""
}

func (m *Event) GetIsProvider() bool {
	if m != nil {
		return m.IsProvider
	}
	return false
}

type isEvent_Metric interface {
	isEvent_Metric()
}

type Event_VersionPayload struct {
	VersionPayload *VersionPayload `protobuf:"bytes,4,opt,name=version_payload,json=versionPayload,proto3,oneof"`
}

type Event_SessionEventPayload struct {
	SessionEventPayload *SessionEventPayload `protobuf:"bytes,5,opt,name=session_event_payload,json=sessionEventPayload,proto3,oneof"`
}

type Event_SessionStatisticsPayload struct {
	SessionStatisticsPayload *SessionStatisticsPayload `protobuf:"bytes,6,opt,name=session_statistics_payload,json=sessionStatisticsPayload,proto3,oneof"`
}

type Event_ProposalPayload struct {
	ProposalPayload *ProposalPayload `protobuf:"bytes,7,opt,name=proposal_payload,json=proposalPayload,proto3,oneof"`
}

type Event_SessionConnectErrorPayload struct {
	SessionConnectErrorPayload *SessionConnectError `protobuf:"bytes,8,opt,name=session_connect_error_payload,json=sessionConnectErrorPayload,proto3,oneof"`
}

type Event_SessionConnectSuccessPayload struct {
	SessionConnectSuccessPayload *SessionConnectSuccess `protobuf:"bytes,9,opt,name=session_connect_success_payload,json=sessionConnectSuccessPayload,proto3,oneof"`
}

func (*Event_VersionPayload) isEvent_Metric() {}

func (*Event_SessionEventPayload) isEvent_Metric() {}

func (*Event_SessionStatisticsPayload) isEvent_Metric() {}

func (*Event_ProposalPayload) isEvent_Metric() {}

func (*Event_SessionConnectErrorPayload) isEvent_Metric() {}

func (*Event_SessionConnectSuccessPayload) isEvent_Metric() {}

func (m *Event) GetMetric() isEvent_Metric {
	if m != nil {
		return m.Metric
	}
	return nil
}

func (m *Event) GetVersionPayload() *VersionPayload {
	if x, ok := m.GetMetric().(*Event_VersionPayload); ok {
		return x.VersionPayload
	}
	return nil
}

func (m *Event) GetSessionEventPayload() *SessionEventPayload {
	if x, ok := m.GetMetric().(*Event_SessionEventPayload); ok {
		return x.SessionEventPayload
	}
	return nil
}

func (m *Event) GetSessionStatisticsPayload() *SessionStatisticsPayload {
	if x, ok := m.GetMetric().(*Event_SessionStatisticsPayload); ok {
		return x.SessionStatisticsPayload
	}
	return nil
}

func (m *Event) GetProposalPayload() *ProposalPayload {
	if x, ok := m.GetMetric().(*Event_ProposalPayload); ok {
		return x.ProposalPayload
	}
	return nil
}

func (m *Event) GetSessionConnectErrorPayload() *SessionConnectError {
	if x, ok := m.GetMetric().(*Event_SessionConnectErrorPayload); ok {
		return x.SessionConnectErrorPayload
	}
	return nil
}

func (m *Event) GetSessionConnectSuccessPayload() *SessionConnectSuccess {
	if x, ok := m.GetMetric().(*Event_SessionConnectSuccessPayload); ok {
		return x.SessionConnectSuccessPayload
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Event) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Event_VersionPayload)(nil),
		(*Event_SessionEventPayload)(nil),
		(*Event_SessionStatisticsPayload)(nil),
		(*Event_ProposalPayload)(nil),
		(*Event_SessionConnectErrorPayload)(nil),
		(*Event_SessionConnectSuccessPayload)(nil),
	}
}

type VersionPayload struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Os                   string   `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Arch                 string   `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionPayload) Reset()         { *m = VersionPayload{} }
func (m *VersionPayload) String() string { return proto.CompactTextString(m) }
func (*VersionPayload) ProtoMessage()    {}
func (*VersionPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_6039342a2ba47b72, []int{2}
}

func (m *VersionPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionPayload.Unmarshal(m, b)
}
func (m *VersionPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionPayload.Marshal(b, m, deterministic)
}
func (m *VersionPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionPayload.Merge(m, src)
}
func (m *VersionPayload) XXX_Size() int {
	return xxx_messageInfo_VersionPayload.Size(m)
}
func (m *VersionPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionPayload.DiscardUnknown(m)
}

var xxx_messageInfo_VersionPayload proto.InternalMessageInfo

func (m *VersionPayload) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *VersionPayload) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *VersionPayload) GetArch() string {
	if m != nil {
		return m.Arch
	}
	return ""
}

type SessionEventPayload struct {
	Session              *SessionPayload `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Event                string          `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SessionEventPayload) Reset()         { *m = SessionEventPayload{} }
func (m *SessionEventPayload) String() string { return proto.CompactTextString(m) }
func (*SessionEventPayload) ProtoMessage()    {}
func (*SessionEventPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_6039342a2ba47b72, []int{3}
}

func (m *SessionEventPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionEventPayload.Unmarshal(m, b)
}
func (m *SessionEventPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionEventPayload.Marshal(b, m, deterministic)
}
func (m *SessionEventPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionEventPayload.Merge(m, src)
}
func (m *SessionEventPayload) XXX_Size() int {
	return xxx_messageInfo_SessionEventPayload.Size(m)
}
func (m *SessionEventPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionEventPayload.DiscardUnknown(m)
}

var xxx_messageInfo_SessionEventPayload proto.InternalMessageInfo

func (m *SessionEventPayload) GetSession() *SessionPayload {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *SessionEventPayload) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

type SessionStatisticsPayload struct {
	Session              *SessionPayload `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	BytesSent            uint64          `protobuf:"varint,2,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesReceived        uint64          `protobuf:"varint,3,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SessionStatisticsPayload) Reset()         { *m = SessionStatisticsPayload{} }
func (m *SessionStatisticsPayload) String() string { return proto.CompactTextString(m) }
func (*SessionStatisticsPayload) ProtoMessage()    {}
func (*SessionStatisticsPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_6039342a2ba47b72, []int{4}
}

func (m *SessionStatisticsPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionStatisticsPayload.Unmarshal(m, b)
}
func (m *SessionStatisticsPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionStatisticsPayload.Marshal(b, m, deterministic)
}
func (m *SessionStatisticsPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionStatisticsPayload.Merge(m, src)
}
func (m *SessionStatisticsPayload) XXX_Size() int {
	return xxx_messageInfo_SessionStatisticsPayload.Size(m)
}
func (m *SessionStatisticsPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionStatisticsPayload.DiscardUnknown(m)
}

var xxx_messageInfo_SessionStatisticsPayload proto.InternalMessageInfo

func (m *SessionStatisticsPayload) GetSession() *SessionPayload {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *SessionStatisticsPayload) GetBytesSent() uint64 {
	if m != nil {
		return m.BytesSent
	}
	return 0
}

func (m *SessionStatisticsPayload) GetBytesReceived() uint64 {
	if m != nil {
		return m.BytesReceived
	}
	return 0
}

type SessionPayload struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServiceType          string   `protobuf:"bytes,2,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	ProviderContry       string   `protobuf:"bytes,3,opt,name=provider_contry,json=providerContry,proto3" json:"provider_contry,omitempty"`
	ConsumerContry       string   `protobuf:"bytes,4,opt,name=consumer_contry,json=consumerContry,proto3" json:"consumer_contry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionPayload) Reset()         { *m = SessionPayload{} }
func (m *SessionPayload) String() string { return proto.CompactTextString(m) }
func (*SessionPayload) ProtoMessage()    {}
func (*SessionPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_6039342a2ba47b72, []int{5}
}

func (m *SessionPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionPayload.Unmarshal(m, b)
}
func (m *SessionPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionPayload.Marshal(b, m, deterministic)
}
func (m *SessionPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionPayload.Merge(m, src)
}
func (m *SessionPayload) XXX_Size() int {
	return xxx_messageInfo_SessionPayload.Size(m)
}
func (m *SessionPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionPayload.DiscardUnknown(m)
}

var xxx_messageInfo_SessionPayload proto.InternalMessageInfo

func (m *SessionPayload) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SessionPayload) GetServiceType() string {
	if m != nil {
		return m.ServiceType
	}
	return ""
}

func (m *SessionPayload) GetProviderContry() string {
	if m != nil {
		return m.ProviderContry
	}
	return ""
}

func (m *SessionPayload) GetConsumerContry() string {
	if m != nil {
		return m.ConsumerContry
	}
	return ""
}

type ProposalPayload struct {
	ProviderId           string          `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	ServiceType          string          `protobuf:"bytes,2,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	Version              *VersionPayload `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	NodeType             string          `protobuf:"bytes,4,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	Country              string          `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ProposalPayload) Reset()         { *m = ProposalPayload{} }
func (m *ProposalPayload) String() string { return proto.CompactTextString(m) }
func (*ProposalPayload) ProtoMessage()    {}
func (*ProposalPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_6039342a2ba47b72, []int{6}
}

func (m *ProposalPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProposalPayload.Unmarshal(m, b)
}
func (m *ProposalPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProposalPayload.Marshal(b, m, deterministic)
}
func (m *ProposalPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProposalPayload.Merge(m, src)
}
func (m *ProposalPayload) XXX_Size() int {
	return xxx_messageInfo_ProposalPayload.Size(m)
}
func (m *ProposalPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_ProposalPayload.DiscardUnknown(m)
}

var xxx_messageInfo_ProposalPayload proto.InternalMessageInfo

func (m *ProposalPayload) GetProviderId() string {
	if m != nil {
		return m.ProviderId
	}
	return ""
}

func (m *ProposalPayload) GetServiceType() string {
	if m != nil {
		return m.ServiceType
	}
	return ""
}

func (m *ProposalPayload) GetVersion() *VersionPayload {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *ProposalPayload) GetNodeType() string {
	if m != nil {
		return m.NodeType
	}
	return ""
}

func (m *ProposalPayload) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

type SessionConnectError struct {
	Session              *SessionPayload `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Reason               string          `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SessionConnectError) Reset()         { *m = SessionConnectError{} }
func (m *SessionConnectError) String() string { return proto.CompactTextString(m) }
func (*SessionConnectError) ProtoMessage()    {}
func (*SessionConnectError) Descriptor() ([]byte, []int) {
	return fileDescriptor_6039342a2ba47b72, []int{7}
}

func (m *SessionConnectError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionConnectError.Unmarshal(m, b)
}
func (m *SessionConnectError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionConnectError.Marshal(b, m, deterministic)
}
func (m *SessionConnectError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionConnectError.Merge(m, src)
}
func (m *SessionConnectError) XXX_Size() int {
	return xxx_messageInfo_SessionConnectError.Size(m)
}
func (m *SessionConnectError) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionConnectError.DiscardUnknown(m)
}

var xxx_messageInfo_SessionConnectError proto.InternalMessageInfo

func (m *SessionConnectError) GetSession() *SessionPayload {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *SessionConnectError) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type SessionConnectSuccess struct {
	Session              *SessionPayload `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SessionConnectSuccess) Reset()         { *m = SessionConnectSuccess{} }
func (m *SessionConnectSuccess) String() string { return proto.CompactTextString(m) }
func (*SessionConnectSuccess) ProtoMessage()    {}
func (*SessionConnectSuccess) Descriptor() ([]byte, []int) {
	return fileDescriptor_6039342a2ba47b72, []int{8}
}

func (m *SessionConnectSuccess) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionConnectSuccess.Unmarshal(m, b)
}
func (m *SessionConnectSuccess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionConnectSuccess.Marshal(b, m, deterministic)
}
func (m *SessionConnectSuccess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionConnectSuccess.Merge(m, src)
}
func (m *SessionConnectSuccess) XXX_Size() int {
	return xxx_messageInfo_SessionConnectSuccess.Size(m)
}
func (m *SessionConnectSuccess) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionConnectSuccess.DiscardUnknown(m)
}

var xxx_messageInfo_SessionConnectSuccess proto.InternalMessageInfo

func (m *SessionConnectSuccess) GetSession() *SessionPayload {
	if m != nil {
		return m.Session
	}
	return nil
}

func init() {
	proto.RegisterType((*Batch)(nil), "metrics.Batch")
	proto.RegisterType((*Event)(nil), "metrics.Event")
	proto.RegisterType((*VersionPayload)(nil), "metrics.VersionPayload")
	proto.RegisterType((*SessionEventPayload)(nil), "metrics.SessionEventPayload")
	proto.RegisterType((*SessionStatisticsPayload)(nil), "metrics.SessionStatisticsPayload")
	proto.RegisterType((*SessionPayload)(nil), "metrics.SessionPayload")
	proto.RegisterType((*ProposalPayload)(nil), "metrics.ProposalPayload")
	proto.RegisterType((*SessionConnectError)(nil), "metrics.SessionConnectError")
	proto.RegisterType((*SessionConnectSuccess)(nil), "metrics.SessionConnectSuccess")
}

func init() { proto.RegisterFile("metrics.proto", fileDescriptor_6039342a2ba47b72) }

var fileDescriptor_6039342a2ba47b72 = []byte{
	// 609 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x5d, 0x4f, 0xd4, 0x40,
	0x14, 0xa5, 0xcb, 0x7e, 0xf5, 0xae, 0x74, 0xcd, 0x20, 0xda, 0x08, 0xc8, 0xd2, 0x44, 0xdd, 0x27,
	0x0c, 0xf8, 0x0f, 0x20, 0x24, 0xe0, 0x83, 0x21, 0xb3, 0xc6, 0x47, 0x6b, 0x99, 0x4e, 0x60, 0x12,
	0xe8, 0x34, 0x73, 0x67, 0x9b, 0xec, 0xef, 0x30, 0xfe, 0x1e, 0x7f, 0x98, 0x2f, 0xa6, 0xf3, 0xd1,
	0xb2, 0xb8, 0x18, 0xb3, 0x6f, 0xcc, 0xb9, 0x87, 0x73, 0xee, 0x9d, 0x7b, 0xa6, 0x0b, 0x5b, 0xf7,
	0x5c, 0x2b, 0xc1, 0xf0, 0xa8, 0x54, 0x52, 0x4b, 0x32, 0x70, 0xc7, 0xe4, 0x03, 0xf4, 0x4e, 0x33,
	0xcd, 0x6e, 0xc9, 0x3b, 0xe8, 0xf3, 0x8a, 0x17, 0x1a, 0xe3, 0x60, 0xb2, 0x39, 0x1d, 0x9d, 0x44,
	0x47, 0xfe, 0x3f, 0xce, 0x6b, 0x98, 0xba, 0x6a, 0xf2, 0xbb, 0x0b, 0x3d, 0x83, 0x90, 0x3d, 0x08,
	0x51, 0xdc, 0x14, 0x99, 0x9e, 0x2b, 0x1e, 0x07, 0x93, 0x60, 0x1a, 0xd2, 0x16, 0x20, 0xbb, 0x10,
	0xea, 0x4c, 0xdd, 0x70, 0x9d, 0x8a, 0x3c, 0xee, 0x98, 0xea, 0xd0, 0x02, 0x97, 0x39, 0x39, 0x80,
	0x91, 0xc0, 0xb4, 0x54, 0xb2, 0x12, 0x39, 0x57, 0xf1, 0xe6, 0x24, 0x98, 0x0e, 0x29, 0x08, 0xbc,
	0x72, 0x08, 0x39, 0x85, 0x71, 0xc5, 0x15, 0x0a, 0x59, 0xa4, 0x65, 0xb6, 0xb8, 0x93, 0x59, 0x1e,
	0x77, 0x27, 0xc1, 0x74, 0x74, 0xf2, 0xaa, 0x69, 0xeb, 0xab, 0xad, 0x5f, 0xd9, 0xf2, 0xc5, 0x06,
	0x8d, 0xaa, 0x25, 0x84, 0x50, 0xd8, 0x41, 0x8e, 0x46, 0xc3, 0xf4, 0xde, 0x28, 0xf5, 0x8c, 0xd2,
	0x5e, 0xa3, 0x34, 0xb3, 0x2c, 0x33, 0x55, 0x2b, 0xb7, 0x8d, 0x7f, 0xc3, 0x24, 0x83, 0xd7, 0x5e,
	0x13, 0x75, 0xa6, 0x05, 0x6a, 0xc1, 0xb0, 0x11, 0xee, 0x1b, 0xe1, 0xc3, 0xc7, 0xc2, 0xb3, 0x86,
	0xd9, 0xaa, 0xc7, 0xf8, 0x44, 0x8d, 0x9c, 0xc3, 0xf3, 0x52, 0xc9, 0x52, 0x62, 0x76, 0xd7, 0x08,
	0x0f, 0x8c, 0x70, 0xdc, 0x08, 0x5f, 0x39, 0x42, 0xab, 0x37, 0x2e, 0x97, 0x21, 0x92, 0xc1, 0xbe,
	0xef, 0x94, 0xc9, 0xa2, 0xe0, 0x4c, 0xa7, 0x5c, 0x29, 0xa9, 0x1a, 0xcd, 0xe1, 0xea, 0x5b, 0x38,
	0xb3, 0xe4, 0xf3, 0x9a, 0x7b, 0xb1, 0x41, 0xfd, 0xb8, 0x0f, 0x61, 0x6f, 0x71, 0x03, 0x07, 0x8f,
	0x2d, 0x70, 0xce, 0x18, 0xc7, 0xf6, 0x46, 0x42, 0x63, 0xf2, 0xe6, 0x09, 0x93, 0x99, 0x65, 0x5f,
	0x6c, 0xd0, 0x3d, 0x5c, 0x55, 0x70, 0x46, 0xa7, 0x43, 0xe8, 0x5b, 0x81, 0xe4, 0x33, 0x44, 0xcb,
	0x7b, 0x27, 0x31, 0x0c, 0xdc, 0xde, 0x5d, 0x06, 0xfd, 0x91, 0x44, 0xd0, 0x91, 0xe8, 0xa2, 0xd7,
	0x91, 0x48, 0x08, 0x74, 0x33, 0xc5, 0x6e, 0x4d, 0xda, 0x42, 0x6a, 0xfe, 0x4e, 0xbe, 0xc1, 0xf6,
	0x8a, 0xed, 0x93, 0x63, 0x18, 0xb8, 0x86, 0x8c, 0xe8, 0xc3, 0xd8, 0x39, 0xba, 0x63, 0x52, 0xcf,
	0x23, 0x2f, 0xa0, 0x67, 0x52, 0xe6, 0x0c, 0xed, 0x21, 0xf9, 0x11, 0x40, 0xfc, 0x54, 0x0a, 0xd6,
	0x71, 0xd9, 0x07, 0xb8, 0x5e, 0x68, 0x8e, 0x29, 0x7a, 0xab, 0x2e, 0x0d, 0x0d, 0x32, 0xab, 0x9f,
	0xe4, 0x5b, 0x88, 0x6c, 0x59, 0x71, 0xc6, 0x45, 0xc5, 0x73, 0x33, 0x6c, 0x97, 0x6e, 0x19, 0x94,
	0x3a, 0x30, 0xf9, 0x19, 0x40, 0xb4, 0xec, 0x50, 0x5f, 0x96, 0xc8, 0xdd, 0x0d, 0x76, 0x44, 0x4e,
	0x0e, 0xe1, 0x19, 0x72, 0x55, 0x09, 0xc6, 0x53, 0xbd, 0x28, 0xb9, 0x9b, 0x6a, 0xe4, 0xb0, 0x2f,
	0x8b, 0x92, 0x93, 0xf7, 0x30, 0xf6, 0x2f, 0xb8, 0xde, 0xbf, 0x56, 0x0b, 0x77, 0xb5, 0x91, 0x87,
	0xcf, 0x0c, 0x5a, 0x13, 0x99, 0x2c, 0x70, 0x7e, 0xdf, 0x12, 0xbb, 0x96, 0xe8, 0x61, 0x4b, 0x4c,
	0x7e, 0x05, 0x30, 0x7e, 0x14, 0xed, 0xfa, 0x53, 0xd1, 0xb8, 0x34, 0x1d, 0x82, 0x87, 0x2e, 0xff,
	0xab, 0xd3, 0xe3, 0x36, 0x23, 0x9b, 0xff, 0xfc, 0x8a, 0xb4, 0xe1, 0xd9, 0x85, 0xb0, 0x90, 0xb9,
	0x93, 0xb4, 0xdd, 0x0e, 0x6b, 0xc0, 0xe8, 0xc5, 0x30, 0x60, 0x72, 0x6e, 0x06, 0xe9, 0xd9, 0xcc,
	0xb9, 0x63, 0xf2, 0xbd, 0xc9, 0xd3, 0xc3, 0x07, 0xb3, 0xce, 0xa6, 0x5f, 0x42, 0x5f, 0xf1, 0x0c,
	0x65, 0xe1, 0x06, 0x72, 0xa7, 0xe4, 0x13, 0xec, 0xac, 0x7c, 0x44, 0x6b, 0x78, 0x5c, 0xf7, 0xcd,
	0x8f, 0xc1, 0xc7, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x95, 0xb4, 0xe3, 0x96, 0x1d, 0x06, 0x00,
	0x00,
}
